import {
  LANDING_PAGE_CONTENT,
  APP_NAVIGATION_CONTENT,
  COURSE_PAGE_CONTENT,
  VACANCY_PAGE_CONTENT,
  MENTORING_PAGE_CONTENT,
  REGISTRATION_FORMS_CONTENT,
  FORMS_PLACEHOLDERS,
  VALIDATION_ERROR_MESSAGES
} from "./Messages.js";
import { COLORS_APP }from "./Colors.js";

export default {
  // Mensagens
  LANDING_PAGE_CONTENT,
  APP_NAVIGATION_CONTENT,
  COURSE_PAGE_CONTENT,
  VACANCY_PAGE_CONTENT,
  MENTORING_PAGE_CONTENT,
  REGISTRATION_FORMS_CONTENT,
  FORMS_PLACEHOLDERS,
  VALIDATION_ERROR_MESSAGES,

  COLORS_APP,
};
